version: "3"

services:

  phpfpm:
    image: modestcoders/php:7.1-fpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock
      - workspace:/var/www/html
      - ./app:/var/www/html/app:delegated
      - ./.git:/var/www/html/.git:delegated
      - ./config:/var/www/html/config:delegated
      - ./composer.json:/var/www/html/composer.json:delegated
      - ./composer.lock:/var/www/html/composer.lock:delegated
      # {files_in_git}
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    depends_on:
      - db

  app:
    build: ./config/dockergento/image/nginx
    ports:
      - 80:8000
    volumes: *appvolumes
    depends_on:
      - phpfpm

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - dbdata:/var/lib/mysql

  node:
    image: modestcoders/node-php:node8-php7.1
    volumes: *appvolumes
    depends_on:
      - phpfpm

  unison:
    image: modestcoders/unison:2.51.2
    volumes:
      - workspace:/var/www/html
      - ./vendor:/sync/vendor
    environment:
      - SYNC_SOURCE_BASE_PATH=/sync
      - SYNC_DESTINATION_BASE_PATH=/var/www/html
      - SYNC_MAX_INOTIFY_WATCHES=60000
    depends_on:
      - phpfpm
    privileged: true

volumes:
  dbdata:
  sockdata:
  workspace:
